baseURL = 'https://danilouie.github.io/'
languageCode = 'en-us'
title = 'Home'
theme = "hugo-coder"
defaultContentLanguage = "en"
enableEmoji = true

[pagination]
  pagerSize = 6

[services]
[services.disqus]
# Enable Disqus comments
# shortname = "yourdiscussshortname"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[markup.highlight]
noClasses = false

[params]
author = "Danielle Louie"
# license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "Danielle Louie's personal website"
keywords = "blog,developer,personal"
info = ["Data Science", "Sustainable Environmental Design"]
avatarURL = "images/Grad_pfp.jpg"
#gravatar = "daniellelouie.07@gmail.com"
dateFormat = "January 2, 2006"
since = 2024
# Git Commit in Footer, uncomment the line below to enable it
commit = "https://github.com/danilouie/blog.git"
# Right To Left, shift content direction for languages such as Arabic
rtl = false
# Specify light/dark colorscheme
# Supported values:
# "auto" (use preference set by browser)
# "dark" (dark background, light foreground)
# "light" (light background, dark foreground) (default)
colorScheme = "auto"
# Hide the toggle button, along with the associated vertical divider
hideColorSchemeToggle = false
# Series see also post count
maxSeeAlsoItems = 5
# Custom CSS
customCSS = []
# Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
customSCSS = []

# Custom JS
customJS = []

# Custom remote JS files
customRemoteJS = []

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa-brands fa-github fa-2x"
weight = 1
url = "https://github.com/danilouie"
target = "_blank"

[[params.social]]
name = "LinkedIn"
icon = "fa-brands fa-linkedin fa-2x"
weight = 4
url = "https://www.linkedin.com/in/danil-e/"
target = "_blank"

# [[params.social]]
# name = "RSS"
# icon = "fa-solid fa-rss fa-2x"
# weight = 6
# url = "https://myhugosite.com/index.xml"
# rel = "alternate"
# type = "application/rss+xml"

[languages.en]
languageName = ":uk:"

[[languages.en.menu.main]]
identifier = "about"
name = "About"
weight = 1
url = "about/"

[[languages.en.menu.main]]
name = "Tutorials"
weight = 2
url = "posts/"

[[languages.en.menu.main]]
name = "Projects"
weight = 3
url = "projects/"

[[languages.en.menu.main]]
name = "Contact/CV"
weight = 4
url = "contact/"

[sitemap]
filename = "sitemap.xml"   
changefreq = "daily"     
priority = 0.5   